server:
  port: 7700

spring:
  application:
    name: microservice-branding-provider
  datasource:
#    url:  jdbc:mysql://172.16.2.95:3306/cluster
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
   root: INFO
   com.zpq.cloud: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/
      #defaultZone: http://peer1:8761/eureka/, http://peer2:8762/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      user  name: zpq
    #appname: BRANDING-MICROSERVICE





